# Databricks notebook source
# MAGIC %sql
# MAGIC USE CATALOG workspace;
# MAGIC 
# MAGIC -- Criação das tabelas de dimensão se não existirem
# MAGIC CREATE TABLE IF NOT EXISTS gold.dim_carro (
# MAGIC   SK_CARRO             bigint generated by default as identity,
# MAGIC   PLACA                varchar(10),
# MAGIC   MARCA                varchar(100),
# MAGIC   MODELO               varchar(100),
# MAGIC   COR                  varchar(10),
# MAGIC   ANO                  int,
# MAGIC   CHASSI               varchar(20)
# MAGIC ) USING DELTA;
# MAGIC 
# MAGIC CREATE TABLE IF NOT EXISTS gold.dim_cliente (
# MAGIC    SK_CLIENTE           bigint generated by default as identity,
# MAGIC    CODIGO_CLIENTE       int,
# MAGIC    NOME                 varchar(50),
# MAGIC    CPF                  varchar(11),
# MAGIC    SEXO                 char(1),
# MAGIC    DATA_NASCIMENTO      date
# MAGIC ) USING DELTA;
# MAGIC 
# MAGIC CREATE TABLE IF NOT EXISTS gold.dim_localidade (
# MAGIC    SK_LOCALIDADE        bigint generated by default as identity,
# MAGIC    CODIGO_MUNICIPIO     int,
# MAGIC    NOME_MUNICIPIO       varchar(100),
# MAGIC    NOME_ESTADO          varchar(100),
# MAGIC    NOME_REGIAO          varchar(100)
# MAGIC ) USING DELTA;
# MAGIC 
# MAGIC CREATE TABLE IF NOT EXISTS gold.fato_sinistro (
# MAGIC    FK_TEMPO             date,
# MAGIC    FK_LOCALIDADE        int,
# MAGIC    FK_CARRO             int,
# MAGIC    FK_CLIENTE           int,
# MAGIC    QTDE_SINISTRO        int
# MAGIC ) USING DELTA;
# MAGIC 
# MAGIC # COMMAND ----------
# MAGIC 
# MAGIC # MAGIC %md
# MAGIC ## Leitura dos dados da Camada Silver
# MAGIC 
# MAGIC # COMMAND ----------
# MAGIC 
# MAGIC df_apolice   = spark.read.format("delta").table("silver.apolice")
# MAGIC df_carro     = spark.read.format("delta").table("silver.carro")
# MAGIC df_cliente   = spark.read.format("delta").table("silver.cliente")
# MAGIC df_endereco  = spark.read.format("delta").table("silver.endereco")
# MAGIC df_estado    = spark.read.format("delta").table("silver.estado")
# MAGIC df_marca     = spark.read.format("delta").table("silver.marca")
# MAGIC df_modelo    = spark.read.format("delta").table("silver.modelo")
# MAGIC df_municipio = spark.read.format("delta").table("silver.municipio")
# MAGIC df_regiao    = spark.read.format("delta").table("silver.regiao")
# MAGIC df_sinistro  = spark.read.format("delta").table("silver.sinistro")
# MAGIC df_telefone  = spark.read.format("delta").table("silver.telefone")
# MAGIC 
# MAGIC # Criando Views Temporárias
# MAGIC df_municipio.createOrReplaceTempView("municipio")
# MAGIC df_estado.createOrReplaceTempView("estado")
# MAGIC df_regiao.createOrReplaceTempView("regiao")
# MAGIC df_apolice.createOrReplaceTempView("apolice")
# MAGIC df_sinistro.createOrReplaceTempView("sinistro")
# MAGIC df_modelo.createOrReplaceTempView("modelo")
# MAGIC df_marca.createOrReplaceTempView("marca")
# MAGIC df_carro.createOrReplaceTempView("carro")
# MAGIC df_cliente.createOrReplaceTempView("cliente")
# MAGIC 
# MAGIC # COMMAND ----------
# MAGIC 
# MAGIC # MAGIC %md
# MAGIC ### Processamento das Dimensões e Fatos
# MAGIC 
# MAGIC # COMMAND ----------
# MAGIC 
# MAGIC # MAGIC %sql
# MAGIC -- 1. Dimensão Carro
# MAGIC WITH carros_relacional AS (
# MAGIC 	SELECT placa,
# MAGIC 		   nome_marca,
# MAGIC 		   nome_modelo,
# MAGIC 		   cor,
# MAGIC 		   ano,
# MAGIC 		   chassi 
# MAGIC 	  FROM carro c
# MAGIC 		   INNER JOIN modelo mo
# MAGIC 		     ON c.codigo_modelo = mo.codigo_modelo
# MAGIC 		   INNER JOIN marca ma
# MAGIC 		     ON mo.codigo_marca = ma.codigo_marca
# MAGIC )
# MAGIC MERGE INTO gold.dim_carro AS c
# MAGIC USING carros_relacional AS cc
# MAGIC ON c.placa = cc.placa   
# MAGIC 
# MAGIC WHEN MATCHED AND (c.marca <> cc.nome_marca OR c.modelo <> cc.nome_modelo OR c.cor <> cc.cor OR c.ano <> cc.ano OR c.chassi <> cc.chassi) THEN
# MAGIC 	UPDATE SET marca  = cc.nome_marca,
# MAGIC 			   modelo = cc.nome_modelo,
# MAGIC 			   cor    = cc.cor,
# MAGIC 			   ano    = cc.ano,
# MAGIC 			   chassi = cc.chassi
# MAGIC 
# MAGIC WHEN NOT MATCHED THEN
# MAGIC 	INSERT (placa, marca, modelo, cor, ano, chassi)
# MAGIC 	VALUES (cc.placa, cc.nome_marca, cc.nome_modelo, cc.cor, cc.ano, cc.chassi);
# MAGIC 
# MAGIC # COMMAND ----------
# MAGIC 
# MAGIC # MAGIC %sql
# MAGIC -- 2. Dimensão Localidade
# MAGIC WITH localidade_relacional AS (
# MAGIC 	SELECT codigo_municipio,
# MAGIC 		   nome_municipio,
# MAGIC 		   nome_estado,
# MAGIC 		   nome_regiao
# MAGIC 	  FROM municipio m
# MAGIC 		   INNER JOIN estado e
# MAGIC 		     ON m.codigo_estado = e.codigo_estado
# MAGIC 		   INNER JOIN regiao r
# MAGIC 		     ON e.codigo_regiao = r.codigo_regiao
# MAGIC )
# MAGIC MERGE INTO gold.dim_localidade AS d
# MAGIC USING localidade_relacional AS r
# MAGIC ON r.codigo_municipio = d.codigo_municipio
# MAGIC 
# MAGIC WHEN MATCHED AND (r.nome_municipio <> d.nome_municipio OR r.nome_estado <> d.nome_estado OR r.nome_regiao <> d.nome_regiao) THEN
# MAGIC 	UPDATE SET nome_municipio = r.nome_municipio,
# MAGIC 			   nome_estado    = r.nome_estado,
# MAGIC 		       nome_regiao    = r.nome_regiao
# MAGIC 
# MAGIC WHEN NOT MATCHED THEN
# MAGIC 	INSERT (codigo_municipio, nome_municipio, nome_estado, nome_regiao)
# MAGIC 	VALUES (r.codigo_municipio, r.nome_municipio, r.nome_estado, r.nome_regiao);
# MAGIC 
# MAGIC # COMMAND ----------
# MAGIC 
# MAGIC # MAGIC %sql
# MAGIC -- 3. Dimensão Cliente
# MAGIC WITH cliente_relacional AS (
# MAGIC 	SELECT codigo_cliente,
# MAGIC 		   nome,
# MAGIC 		   cpf,
# MAGIC 		   sexo,
# MAGIC 		   data_nascimento
# MAGIC 	  FROM cliente
# MAGIC )
# MAGIC MERGE INTO gold.dim_cliente AS d
# MAGIC USING cliente_relacional AS r
# MAGIC ON r.codigo_cliente = d.codigo_cliente   
# MAGIC 
# MAGIC WHEN MATCHED AND (r.nome <> d.nome OR r.cpf <> d.cpf OR r.sexo <> d.sexo OR r.data_nascimento <> d.data_nascimento) THEN
# MAGIC 	UPDATE SET nome            = r.nome,
# MAGIC 			   cpf             = r.cpf,
# MAGIC 			   sexo            = r.sexo,
# MAGIC 			   data_nascimento = r.data_nascimento
# MAGIC 
# MAGIC WHEN NOT MATCHED THEN
# MAGIC 	INSERT (codigo_cliente, nome, cpf, sexo, data_nascimento)
# MAGIC 	VALUES (r.codigo_cliente, r.nome, r.cpf, r.sexo, r.data_nascimento);
# MAGIC 
# MAGIC # COMMAND ----------
# MAGIC 
# MAGIC from pyspark.sql.functions import expr, date_format
# MAGIC 
# MAGIC # Define o intervalo de datas desejado
# MAGIC data_inicial = "2023-01-01"
# MAGIC data_final = "2026-12-31"
# MAGIC 
# MAGIC # Calcula o número de dias no intervalo
# MAGIC num_dias = spark.sql(f"SELECT datediff('{data_final}', '{data_inicial}')").collect()[0][0]
# MAGIC 
# MAGIC # Cria um DataFrame com uma coluna contendo uma sequência de datas
# MAGIC df_calendario = spark.range(0, num_dias + 1) \
# MAGIC     .selectExpr(f"date_add(to_date('{data_inicial}'), CAST(id AS INT)) AS Data")
# MAGIC 
# MAGIC # Extrai os componentes de data
# MAGIC df_tempo = df_calendario.selectExpr(
# MAGIC     "Data",
# MAGIC     "year(Data) AS Ano",
# MAGIC     "month(Data) AS Mes",
# MAGIC        "(CASE month(Data) \
# MAGIC         WHEN 1 THEN 'JANEIRO' \
# MAGIC         WHEN 2 THEN 'FEVEREIRO' \
# MAGIC         WHEN 3 THEN 'MARCO' \
# MAGIC         WHEN 4 THEN 'ABRIL' \
# MAGIC         WHEN 5 THEN 'MAIO' \
# MAGIC         WHEN 6 THEN 'JUNHO' \
# MAGIC         WHEN 7 THEN 'JULHO' \
# MAGIC         WHEN 8 THEN 'AGOSTO' \
# MAGIC         WHEN 9 THEN 'SETEMBRO' \
# MAGIC         WHEN 10 THEN 'OUTUBRO' \
# MAGIC         WHEN 11 THEN 'NOVEMBRO' \
# MAGIC         WHEN 12 THEN 'DEZEMBRO' \
# MAGIC     END) AS NomeMes",
# MAGIC     "day(Data) AS Dia",
# MAGIC     "(CASE dayofweek(Data) \
# MAGIC         WHEN 1 THEN 'DOMINGO' \
# MAGIC         WHEN 2 THEN 'SEGUNDA-FEIRA' \
# MAGIC         WHEN 3 THEN 'TERCA-FEIRA' \
# MAGIC         WHEN 4 THEN 'QUARTA-FEIRA' \
# MAGIC         WHEN 5 THEN 'QUINTA-FEIRA' \
# MAGIC         WHEN 6 THEN 'SEXTA-FEIRA' \
# MAGIC         WHEN 7 THEN 'SABADO' \
# MAGIC     END) AS NomeDiaSemana",
# MAGIC     "dayofweek(Data) AS NumeroDiaSemana"
# MAGIC )
# MAGIC 
# MAGIC df_tempo.write.mode('overwrite').saveAsTable("gold.dim_tempo", format="delta")
# MAGIC 
# MAGIC # COMMAND ----------
# MAGIC 
# MAGIC # MAGIC %sql
# MAGIC -- 5. Fato Sinistro
# MAGIC WITH apolice_cliente AS (
# MAGIC 	SELECT a.codigo_cliente, placa FROM apolice a INNER JOIN cliente c ON a.codigo_cliente = c.codigo_cliente
# MAGIC )
# MAGIC INSERT INTO gold.fato_sinistro
# MAGIC SELECT data_sinistro AS fk_tempo,
# MAGIC        sk_localidade,
# MAGIC 	   sk_carro,
# MAGIC 	   sk_cliente,
# MAGIC 	   COUNT(1) AS qtde_sinistro
# MAGIC FROM sinistro r
# MAGIC        INNER JOIN gold.dim_carro dcar
# MAGIC 	     ON r.placa = dcar.placa
# MAGIC 	   INNER JOIN apolice_cliente ac
# MAGIC 	     ON ac.placa = r.placa
# MAGIC 	   INNER JOIN gold.dim_cliente dcli
# MAGIC 	     ON ac.codigo_cliente = dcli.codigo_cliente
# MAGIC 	   INNER JOIN gold.dim_localidade dloc
# MAGIC 	     ON r.local_sinistro = dloc.codigo_municipio
# MAGIC 	   INNER JOIN gold.dim_tempo dtem
# MAGIC 	     ON r.data_sinistro = dtem.data
# MAGIC GROUP BY data_sinistro,
# MAGIC        sk_localidade,
# MAGIC 	   sk_carro,
# MAGIC 	   sk_cliente;

